### ISSUE TITLE
link to file on GitHub for editing

### ISSUE THREAD

**Issue by afeld** [cloudfoundry/docs-book-cloudfoundry#11]
Took me a bit of Googling to find this repository...would be useful to have a link to "edit this on GitHub" for pages within http://docs.cloudfoundry.org.

**Comment by animatedmax** [comment]
Hi @afeld I've moved this story to the Pivotal Pub Tools tracker. They'll be coming up with an easier way for people to give feedback and suggest changes to topics. Thank you much!

**Comment by animatedmax** [comment]
This functionality was added to Bookbinder in Release [v7.4.0](https://github.com/pivotal-cf/bookbinder/releases/tag/v7.4.0)

**Comment by afeld** [comment]
:tada:
