### ISSUE TITLE
README instructions fail saying docs-layout-repo not found.

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/docs-book-cloudfoundry#21]
I get this error message:

```
Amits-MacBook-Pro:docs-book-cloudfoundry agupta$ bin/bookbinder bind local
  skipping (not found) /Users/agupta/workspace/docs-layout-repo
The method copy_contents cannot copy the contents of the directory '/Users/agupta/workspace/docs-layout-repo' because it was not found.
```

Once I clone the `docs-layout-repo` sibling to this repo, things work fine.  README should be updated to describe this requirement, or it should work without it please.  I know in the past it worked without it.  Also, any reason why that repo is in the `pivotal-cf` org and not `cloudfoundry`?

**Comment by animatedmax** [comment]
Hi Amit-PivotalLabs,

It looks like we added a note to the top of the README, but no one closed out this issue.

The following note is now at the top of the cloudfoundry/docs-book-cloudfoundry repo:

**Breaking Change**: This book now uses a centralized layout repository, docs-layout-repo.
You must clone this repository to run bookbinder bind local.

The centralized layout repository is specified as the value of the layout_repo key in the config.yml file. Bookbinder uses this centralized layout repository by default, but files in the book's master_middleman/source directory override files in the centralized layout repository if they have the same name.

**Comment by animatedmax** [comment]
Thank you for raising this issue!

**Comment by Amit-PivotalLabs** [comment]
@animatedmax why not just add this to the contributing section?  If I want to contribute, I'd like to scroll directly to the contributing section, and follow those steps so that I can start working.

**Comment by jbheron** [comment]
Thanks, Amit, we've added that detail for those who head straight to the 'Contributing' section.
