### ISSUE TITLE
As a contributor, I want to easily find the source file for any given page

### ISSUE THREAD

**Issue by afeld** [cloudfoundry/docs-book-cloudfoundry#32]
I've been wanting to contribute more and more to the Cloud Foundry documentation, but when I come across a page that I want to modify, it's hard to find the corresponding Markdown file across the various repositories. It would be great to have an "improve this page" link to take the contributor to the web editing view on GitHub. Thanks!

**Comment by mogul** [comment]
Oh yes, please... I've wanted to improve docs myself but ran into exactly the same friction.

**Comment by jbheron** [comment]
Hi, @afeld and @mogul, thanks for taking an interest in our documentation. We have added this feature to the bottom of every page as link "View the source for this page in GitHub". We look forward to your PRs. 
Thanks again

**Comment by afeld** [comment]
Ha, I apparently wanted this badly enough that I filed an issue twice :expressionless: https://github.com/cloudfoundry/docs-book-cloudfoundry/issues/11 Thanks!

**Comment by afeld** [comment]
Hmm, this was there for a while, but seems to have disappeared...?

**Comment by kimahoff** [comment]
Hi @afeld -- the feature was turned off by mistake. I actually thought we turned it back on a week or so ago, so I'm surprised to see it's still missing; not sure if this is evidence of a bug. We'll look into it and make sure we get the links back, though. Thanks!
