### ISSUE TITLE
Modified dates broken across all cf docs?

### ISSUE THREAD

**Issue by SamuelMarks** [cloudfoundry/docs-book-cloudfoundry#37]
> Page last updated: Invalid Date NaN, NaN

Examples:
- http://docs.cloudfoundry.org/deploying/common/consul-security.html
- http://docs.cloudfoundry.org/concepts/high-availability.html

**Comment by kimahoff** [comment]
Hi @SamuelMarks ,
Our team is not able to reproduce this problem. When we view those two pages, the Last Modified date looks fine to us. Are you still seeing the problem? Can you give us any more context around when or where you saw this?

Thanks!

**Comment by animatedmax** [comment]
Hi @SamuelMarks , 
We've reproduced the issue by opening the pages in Firefox v44.0.2. I'm raising a bug with the team responsible for updating the modified date code. Thank you very much for pointing out this issue!

**Comment by animatedmax** [comment]
Hi @SamuelMarks This issue should now be resolved. Thank you!
