### ISSUE TITLE
Search results get cut off in Safari

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/docs-book-cloudfoundry#38]
While the search of the documentation on [https://docs.cloudfoundry.org](https://docs.cloudfoundry.org) works well in Chrome, in Safari (and possibly other browsers) the results get cut off. The search results panel gets hidden by the main content and it's impossible to read the search results. I am using Safari `9.0.3` on Mac OS X `10.11.3`.

**Comment by mastertinner** [comment]
This was fixed with b4bf3b0eb15f2ab1fae356d8277d76a91c405117. However, I'm experiencing a new issue now. The search input field seems to be completely gone. Is that related to this fix?

**Comment by animatedmax** [comment]
Hi @mastertinner Yes, I believe this is related to the fix. We're still looking into it. Thanks for you patience.

**Comment by animatedmax** [comment]
Hi @mastertinner The search box is back, and the issue with results bing cut off in Safari should now be resolved. Please let us know if you are still having any problems.

**Comment by mastertinner** [comment]
It is back and the search is not cut off anymore! Thanks, @animatedmax!
