### ISSUE TITLE
"Workflow for Contributing" suggested improvements

### ISSUE THREAD

**Issue by Dannyzen** [cloudfoundry/docs-book-cloudfoundry#40]
Hey there, 

We noticed that the [Contributing Pull Requests](https://github.com/cloudfoundry/docs-book-cloudfoundry#contributing-pull-requests) section of the `README` could be updated to better explain newer functionality that bookbinder provides. I've listed steps below (originally penned by @shalako) that may make it easier for others to make changes to the documentation. 

> 1. fork the content repo you want to make a contribution to
> 
>   Examples: 
>    The docs that describes buildpacks can be found at http://docs.cloudfoundry.org/buildpacks/index.html. The content repo is: https://github.com/cloudfoundry/docs-buildpacks
>   The docs that describes for users how to push apps, create service instances, etc. can be found at: http://docs.cloudfoundry.org/devguide/services/. The content repo is: https://github.com/cloudfoundry/docs-dev-guide
> 
> 2.  clone your fork of the content repo 
> 3.     cd into book-repo and run $ bin/bookbinder watch
> 4.     point your browser at localhost:4567
> 5.     Make your edits; on save your browser page will reload with changes
> 6.     commit changes, rebase from upstream, and push to your fork
> 7.     Submit a PR from your fork to the original repos
> 8.     The Docs team merges the PR
> 9.     The Docs team pushes the book apps to production

Thanks for your help!

**Comment by mamorrison** [comment]
Hi @Dannyzen, we updated the README based on your recommendations. Take a look and let us know what you think - https://github.com/cloudfoundry/docs-book-cloudfoundry#contributing-pull-requests. If you don't have any additional input, we'll go ahead and close this bug.

**Comment by Dannyzen** [comment]
@mamorrison awesome! 

on-topic / off-topic: In the future it would be even cooler if all the technical work could be done by a docker container, exposing the port and file system to the host machine so I could make edits and view the container's webserver from my computer. I actually [started work on this here](https://github.com/Dannyzen/cloudfoundry-docs-docker/blob/master/Dockerfile) if you're interested in pairing and finishing it up I'd be open!

**Comment by kimahoff** [comment]
Hey @Dannyzen -- our Pub Tools team, who develops our tools, is probably the correct audience for that suggestion. @animatedmax ^^^
