### ISSUE TITLE
Add "shared_domain" variable

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/docs-book-cloudfoundry#42]
For Cloud Foundry providers it would be nice, if we could use a specific shared domain that we offer, in the docs. For example the page https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#domains-dns would be easier to comprehend for new users if it included a specific example (e.g. "cfapps.io" for PWS or "scapp.io" for Swisscom) instead of using the generic ".shared-domain.com". I would therefore vote to create a new variable `shared_domain` in `config.yml` and use it everywhere instead of examples like "shared-domain.com". The Cloud Foundry docs could still set that variable to "shared-domain.com" to stay generic.

If you guys agree, I can make a PR.

**Comment by mastertinner** [comment]
I just noticed that we already have this variable as `app_domain`. That resolves this issue.

**Comment by kimahoff** [comment]
Thanks @mastertinner !
