### ISSUE TITLE
Can't deploy to a recent CF 

### ISSUE THREAD

**Issue by bleach** [cloudfoundry/docs-book-cloudfoundry#66]
I tried deploying to CF v251 in order to be able to test some copy changes in usability testing.

I hit the problems described in cloudfoundry/ruby-buildpack#75 because this app tries to use ruby 2.3.0, which is not supported by recent ruby buildpacks.

As pointed out in that issue, this happens because `final_app/Gemfile` contains this line:

`ruby '2.3.0'`

I don't really understand how to fix this myself.

**Comment by ljarzynski** [comment]
Hi @bleach! Good point. We should document what users should do in this case. I  know for our (docs) apps, we do one of two things: 1.) mod final_app/Gemfile to use 2.3.3 OR 2.) push using a specific buildpack that does support 2.3.0. But we should probably find out the "official" stance and document it.

**Comment by bleach** [comment]
Ok. I'm using 1) now. 2) is not an option for me, as custom buildpacks are not enabled on our CF

**Comment by bleach** [comment]
Thanks for replying!

**Comment by ljarzynski** [comment]
Hey @bleach! Just wanted to let you know that I pushed an addition to the Ruby buildpack documentation: https://github.com/cloudfoundry/docs-buildpacks/commit/7e45db12325cc6058a4fbd747f99cbd6d442c82a.

**Comment by bleach** [comment]
@ljarzynski thanks for looking at this.

I think the drawback to suggesting that users select old buildpack versions in the documentation is that it encourages users to install unsupported ruby versions. This will likely leave them missing security patches. It's a short term measure, that at best delays the need to make the app use a newer ruby. I'd encourage you to revert the change you made.

What I was hoping for was that *this* application could be brought up to date to run on the latest ruby buildpack. I had a go at this previously, but ran into the problems described, which the ruby buildpack team pointed out were due to `final_app/Gemfile` still specifying the old version. Ideally someone who understands more about the internals of this app would be able to suggest how it could be made to work on the latest ruby buildpack version.

**Comment by ljarzynski** [comment]
@bleach Thank you for the feedback. Given that, I agree it would be best to remove the suggestion to use an older buildpack. Do you think we should leave the the second bit in about updating the Gemfile?

**Comment by bentarnoff** [comment]
@bleach Just wanted to bump this to make sure you saw @ljarzynski's question.

**Comment by bleach** [comment]
@ljarzynski @bentarnoff apologies, I hadn't seen the question.

The ruby buildpack documentation seems to already have clear guidance on specifying ruby versions: http://docs.cloudfoundry.org/buildpacks/ruby/index.html#supported_versions

IMO the README for this repo, `docs-book-cloudfoundry` could be updated to state what a user is supposed to do to deploy to a recent CF. Or (my preference) the build process could be changed so it works out of the box (I'm not sure how to do this though).

But my original problem is solved, albeit in a non-ideal way.
