### ISSUE TITLE
cloudfoundry/docs-uaa not found

### ISSUE THREAD

**Issue by mastertinner** [cloudfoundry/docs-book-cloudfoundry#71]
When trying to build my [book](https://github.com/swisscom/docs-appcloud-book) (which is an up to date fork of this one), it asks me for a username and password for the repo `cloudfoundry/docs-uaa`. Is this just a misconfiguration or is this repo not public yet? I am currently stuck because I cannot build my docs.

**Comment by jncd** [comment]
Very sorry about this, @mastertinner 
Whoever made the repo for us, left it as a private repo. It should have been public.
I changed the status to public now. That should fix it — let me know if you still have problems.

**Comment by mastertinner** [comment]
That fixed it. Thanks, @jncd!
