### ISSUE TITLE
Docs site does not redirect to HTTPS

### ISSUE THREAD

**Issue by jonathaningram** [cloudfoundry/docs-book-cloudfoundry#75]
http://docs.cloudfoundry.org/cf-cli does not automatically redirect to HTTPS.

```
$ curl -I http://docs.cloudfoundry.org/cf-cli/
HTTP/1.1 200 OK
...
```

Expected something like:

```
$ curl -I http://www.cloudfoundry.org/
HTTP/1.1 301 Moved Permanently
Content-Type: text/html; charset=UTF-8
Location: https://www.cloudfoundry.org/
...
```

Not sure if there's any reason why HTTPS couldn't or shouldn't be enforced?

Originally reported here: https://github.com/cloudfoundry/cli/issues/1306

**Comment by animatedmax** [comment]
Hi @jonathaningram This issue should now be resolved.
