### ISSUE TITLE
Doc home page is lacking the "Create a PR ..." hint

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-book-cloudfoundry#85]
https://docs.cloudfoundry.org/ is lacking the usual "Create a pull request or raise an issue on the source for this page in GitHub" mentionned at https://docs.cloudfoundry.org/concepts/contribute.html#contribute

Findind that this PR to this page actually match https://github.com/cloudfoundry/docs-book-cloudfoundry/blob/master/master_middleman/source/index.html.md.erb took me a while of googling

This is a refinement over #30

**Comment by mlimonczenko** [comment]
Hello, @gberche-orange! I'm not sure I fully understand the issue.

It sounds like you are looking for a contribute link at the bottom of the homepage. I think the logic of our publishing tools would require us to make something custom.

**Comment by gberche-orange** [comment]
> It sounds like you are looking for a contribute link at the bottom of the homepage.

Yes 

> I think the logic of our publishing tools would require us to make something custom.

If this can be accomodated, I believe this will make it much easier for the homepage to be more up-to-date by getting user contribs.

**Comment by mlimonczenko** [comment]
Hello @gberche-orange,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.

**Comment by gberche-orange** [comment]
@mlimonczenko this issue is still relevant. Any chance for you to reopen it instead of requesting a new issue that would duplicate this one ?

**Comment by animatedmax** [comment]
Hi @gberche-orange I just added the link to the source file to the bottom of the page https://docs.cloudfoundry.org/

**Comment by gberche-orange** [comment]
great, thanks @animatedmax !
