### ISSUE TITLE
Wrong link for Cloud Foundry Concepts > General Concepts > App Container Lifecycle

### ISSUE THREAD

**Issue by antimatter96** [cloudfoundry/docs-book-cloudfoundry#87]
Go to https://www.cloudfoundry.org/get-started/#cf-concepts

Scroll to Cloud Foundry Concepts > General Concepts 
"App Container Lifecycle" opens "https://www.cloudfoundry.org/devguide/deploy-apps/app-lifecycle.html"

It should open "https://docs.cloudfoundry.org/devguide/deploy-apps/app-lifecycle.html"

All other links work fine

**Comment by emalm** [comment]
Hey, @antimatter96, this seems to be an issue with the main CF site, which is separate from the CF docs site. Pinging @swarnap and @christopherclark at the CF Foundation in case they know who could fix the link destination on the main site.

**Comment by christopherclark** [comment]
I'll have this fixed soon.  Thanks @antimatter96 @emalm

**Comment by christopherclark** [comment]
Fixed. Thanks again for the heads up!
