### ISSUE TITLE
Duplicate subnav navigation to Service Mesh Architecture

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/docs-book-cloudfoundry#90]
There are two sub-nav menus for Service Mesh Architecture.

__Actual__
https://github.com/cloudfoundry/docs-book-cloudfoundry/blob/6b4d57898cbe9dec46fc52078a96e2dac8c61190/master_middleman/source/subnavs/_cf-subnav.erb#L72-L78

__Expected__
Only one link.

**Comment by mlimonczenko** [comment]
This is fixed! Thank you so much @wfernandes.
